/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author Total Energies
 */
public class FrmMenuSecretario extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuSecretario
     */
    public FrmMenuSecretario(String txtLogado) {
        initComponents();
        this.setLocationRelativeTo(null); // centraliza o JFrame
        this.setResizable(false); // torna o JFrame não redimensionável
        lblLogadoComo.setText(txtLogado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInserirLivro = new javax.swing.JButton();
        btnListarLivro = new javax.swing.JButton();
        btnInserirCd = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnInserirRevista = new javax.swing.JButton();
        btnListarRevista = new javax.swing.JButton();
        btnInserirUsuario = new javax.swing.JButton();
        btnListarUsuario = new javax.swing.JButton();
        btnInserirAutor = new javax.swing.JButton();
        btnListarAutor = new javax.swing.JButton();
        lblLogadoComo = new javax.swing.JLabel();
        inserirEmprestimo = new javax.swing.JButton();
        btnListarAutoria = new javax.swing.JButton();
        btnInserirAutoria = new javax.swing.JButton();
        listarItensEmprestados = new javax.swing.JButton();
        listarItensDisponiveis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Bibliotecário");

        btnInserirLivro.setText("Inserir Livro");
        btnInserirLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirLivroActionPerformed(evt);
            }
        });

        btnListarLivro.setText("Listar Livro");
        btnListarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLivroActionPerformed(evt);
            }
        });

        btnInserirCd.setText("Inserir CD");
        btnInserirCd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirCdActionPerformed(evt);
            }
        });

        btnListar.setText("Listar CD");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnInserirRevista.setText("Inserir Revista");
        btnInserirRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirRevistaActionPerformed(evt);
            }
        });

        btnListarRevista.setText("Listar Revista");
        btnListarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarRevistaActionPerformed(evt);
            }
        });

        btnInserirUsuario.setText("Inserir Usuário");
        btnInserirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirUsuarioActionPerformed(evt);
            }
        });

        btnListarUsuario.setText("Listar Usuário");
        btnListarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarUsuarioActionPerformed(evt);
            }
        });

        btnInserirAutor.setText("Inserir Autor");
        btnInserirAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirAutorActionPerformed(evt);
            }
        });

        btnListarAutor.setText("Listar Autor");
        btnListarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAutorActionPerformed(evt);
            }
        });

        inserirEmprestimo.setText("Inserir Empréstimo");
        inserirEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirEmprestimoActionPerformed(evt);
            }
        });

        btnListarAutoria.setText("Listar Autoria");
        btnListarAutoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAutoriaActionPerformed(evt);
            }
        });

        btnInserirAutoria.setText("Inserir Autoria");
        btnInserirAutoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirAutoriaActionPerformed(evt);
            }
        });

        listarItensEmprestados.setText("Listar Itens Emprestados");
        listarItensEmprestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarItensEmprestadosActionPerformed(evt);
            }
        });

        listarItensDisponiveis.setText("Listar Itens Disponíveis");
        listarItensDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarItensDisponiveisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInserirAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInserirUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInserirRevista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInserirCd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInserirLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInserirAutoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogadoComo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnListarLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListarAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListarRevista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListarAutoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(inserirEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listarItensDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listarItensEmprestados, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirLivro)
                    .addComponent(btnListarLivro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirCd)
                    .addComponent(btnListar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirRevista)
                    .addComponent(btnListarRevista))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirUsuario)
                    .addComponent(btnListarUsuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirAutor)
                    .addComponent(btnListarAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarAutoria)
                    .addComponent(btnInserirAutoria))
                .addGap(8, 8, 8)
                .addComponent(inserirEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listarItensEmprestados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listarItensDisponiveis)
                .addGap(18, 18, 18)
                .addComponent(lblLogadoComo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirLivroActionPerformed
        FrmAddLivro frmLivro = new FrmAddLivro(lblLogadoComo.getText().toString());
        frmLivro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInserirLivroActionPerformed

    private void btnListarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLivroActionPerformed
        FrmListarLivro frmLivro = new FrmListarLivro(lblLogadoComo.getText().toString());
        frmLivro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListarLivroActionPerformed

    private void btnInserirCdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirCdActionPerformed
        FrmAddCd frmCD = new FrmAddCd(lblLogadoComo.getText().toString());
        frmCD.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInserirCdActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
          FrmListarCd cd = new FrmListarCd(lblLogadoComo.getText().toString());
          cd.setVisible(true);
          dispose();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnInserirRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirRevistaActionPerformed
        FrmAddRevista revista = new FrmAddRevista(lblLogadoComo.getText().toString());
        revista.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInserirRevistaActionPerformed

    private void btnListarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarRevistaActionPerformed
        FrmListarRevista revista = new FrmListarRevista(lblLogadoComo.getText().toString());
        revista.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListarRevistaActionPerformed

    private void btnInserirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirUsuarioActionPerformed
        FrmAddUsuario usuario = new FrmAddUsuario(lblLogadoComo.getText().toString());
        usuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInserirUsuarioActionPerformed

    private void btnListarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarUsuarioActionPerformed
        FrmListarUsuario usuario = new FrmListarUsuario(lblLogadoComo.getText().toString());
        usuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListarUsuarioActionPerformed

    private void btnInserirAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirAutorActionPerformed
        FrmAddAutor autor = new FrmAddAutor(lblLogadoComo.getText().toString());
        autor.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInserirAutorActionPerformed

    private void btnListarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAutorActionPerformed
        FrmListarAutor autor = new FrmListarAutor(lblLogadoComo.getText().toString());
        autor.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListarAutorActionPerformed

    private void inserirEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirEmprestimoActionPerformed
           FrmAddEmprestimo emp = new FrmAddEmprestimo(lblLogadoComo.getText().toString());
           emp.setVisible(true);
           dispose();
    }//GEN-LAST:event_inserirEmprestimoActionPerformed

    private void btnListarAutoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAutoriaActionPerformed
        FrmListarAutoria autoria = new FrmListarAutoria(lblLogadoComo.getText().toString());
        autoria.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListarAutoriaActionPerformed

    private void btnInserirAutoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirAutoriaActionPerformed
        FrmAddAutoria autoria = new FrmAddAutoria(lblLogadoComo.getText().toString());
        autoria.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInserirAutoriaActionPerformed

    private void listarItensEmprestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarItensEmprestadosActionPerformed
        FrmListarItensEmprestados emp = new FrmListarItensEmprestados(lblLogadoComo.getText().toString());
        emp.setVisible(true);
        dispose();
    }//GEN-LAST:event_listarItensEmprestadosActionPerformed

    private void listarItensDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarItensDisponiveisActionPerformed
        FrmListarItensDisponiveis itensDisp = new FrmListarItensDisponiveis(lblLogadoComo.getText().toString());
        itensDisp.setVisible(true);
        dispose();
    }//GEN-LAST:event_listarItensDisponiveisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuSecretario("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserirAutor;
    private javax.swing.JButton btnInserirAutoria;
    private javax.swing.JButton btnInserirCd;
    private javax.swing.JButton btnInserirLivro;
    private javax.swing.JButton btnInserirRevista;
    private javax.swing.JButton btnInserirUsuario;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnListarAutor;
    private javax.swing.JButton btnListarAutoria;
    private javax.swing.JButton btnListarLivro;
    private javax.swing.JButton btnListarRevista;
    private javax.swing.JButton btnListarUsuario;
    private javax.swing.JButton inserirEmprestimo;
    private javax.swing.JLabel lblLogadoComo;
    private javax.swing.JButton listarItensDisponiveis;
    private javax.swing.JButton listarItensEmprestados;
    // End of variables declaration//GEN-END:variables
}
